server:
  port: 8080

spring:
  application:
    name: "blog"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    schemas: [ 'blog' ]
    table: schema_version
    enabled: true
    validate-on-migrate: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: metrics, health
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true