DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID         BIGSERIAL PRIMARY KEY,
    SURNAME    VARCHAR(255) NOT NULL,
    NAME       VARCHAR(255) NOT NULL,
    PATRONYMIC VARCHAR(255)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    ID        BIGSERIAL PRIMARY KEY,
    NAME      VARCHAR(255) NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    GENRE_ID  BIGINT NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID)
);