CREATE SEQUENCE AUTHOR_SEQUENCE START WITH 1;
CREATE SEQUENCE GENRE_SEQUENCE START WITH 1;
CREATE SEQUENCE BOOK_SEQUENCE START WITH 1;

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID         BIGINT PRIMARY KEY,
    NAME       VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    ID        BIGINT PRIMARY KEY,
    NAME      VARCHAR(255) NOT NULL,
    GENRE_ID  BIGINT       NOT NULL,
    AUTHOR_ID  BIGINT       NOT NULL,
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID)
);